-- ============================================
-- BREWLINK DATABASE SCHEMA
-- ============================================

-- 1. PROFILES
-- Stores basic information about each student.

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null,
  last_name text,
  major text,
  academic_year text,
  bio text,
  career_goal text,
  profile_photo_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


-- 2. INTERESTS
-- Master list of interests/career areas.

create table public.interests (
  id bigint generated by default as identity primary key,
  name text unique not null,
  category text
);


-- 3. USER INTERESTS
-- Connects students to their selected interests.

create table public.user_interests (
  user_id uuid references public.profiles(id) on delete cascade,
  interest_id bigint references public.interests(id) on delete cascade,
  primary key (user_id, interest_id)
);


-- 4. CLUBS
-- UCSD clubs and organizations.

create table public.clubs (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  created_at timestamptz default now()
);


-- 5. USER CLUBS
-- Connects students to clubs.

create table public.user_clubs (
  user_id uuid references public.profiles(id) on delete cascade,
  club_id bigint references public.clubs(id) on delete cascade,
  primary key (user_id, club_id)
);


-- 6. PROJECTS
-- Projects that students want to showcase.

create table public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  title text not null,
  description text,
  created_at timestamptz default now()
);


-- 7. AVAILABILITY
-- Recurring weekly availability.

create table public.availability (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  start_time time not null,
  end_time time not null,
  created_at timestamptz default now(),
  check (end_time > start_time)
);


-- 8. MATCH PREFERENCES
-- Controls what types of students a user wants to meet.

create table public.match_preferences (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  same_major boolean default true,
  similar_career_interests boolean default true,
  outside_major boolean default false,
  upperclassmen boolean default false,
  mentors boolean default false,
  project_collaborators boolean default false,
  frequency text default 'monthly'
);


-- 9. CONNECTIONS
-- Records when one student expresses interest in another.

create table public.connections (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) on delete cascade,
  receiver_id uuid references public.profiles(id) on delete cascade,
  status text default 'pending',
  created_at timestamptz default now(),
  unique(sender_id, receiver_id),
  check (sender_id <> receiver_id)
);


-- 10. MATCHES
-- Created when two students mutually connect.

create table public.matches (
  id bigint generated by default as identity primary key,
  user_1_id uuid references public.profiles(id) on delete cascade,
  user_2_id uuid references public.profiles(id) on delete cascade,
  match_score numeric(5,2),
  status text default 'active',
  created_at timestamptz default now(),
  check (user_1_id <> user_2_id)
);


-- 11. MESSAGES
-- Messages between matched students.

create table public.messages (
  id bigint generated by default as identity primary key,
  match_id bigint references public.matches(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete cascade,
  message text not null,
  created_at timestamptz default now()
);


-- 12. MEETINGS
-- Scheduled coffee chats.

create table public.meetings (
  id bigint generated by default as identity primary key,
  match_id bigint references public.matches(id) on delete cascade,
  scheduled_date date,
  start_time time,
  location text,
  status text default 'scheduled',
  created_at timestamptz default now()
);


-- 13. FEEDBACK
-- Post-meeting feedback used to improve matching.

create table public.feedback (
  id bigint generated by default as identity primary key,
  meeting_id bigint references public.meetings(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  rating integer check (rating between 1 and 5),
  match_quality text,
  would_meet_again boolean,
  comments text,
  created_at timestamptz default now()
);